### ISSUE TITLE
Support content-script shadow-dom

### ISSUE THREAD

**Issue by ghost** [mubaidr/vite-vue3-chrome-extension-v3#24]

**Comment by mubaidr** [comment]
Can you please provide more info? Relevant links etc?

**Comment by ghost** [comment]
@mubaidr hi  These are related links ~  
https://github.com/crxjs/chrome-extension-tools/discussions/239#discussioncomment-3748016

**Comment by mubaidr** [comment]
Are you willing to do a pull request to support this feature?

**Comment by ghost** [comment]
Of course, I can give it a try

**Comment by ghost** [comment]
@mubaidr  hi I tried and implemented it when I had time. But obviously, it is not suitable to use vue-router with shadow-dom as it will affect the page routing. So I choose to close this issue.
