### ISSUE TITLE
Source files (.ts) in dist folder

### ISSUE THREAD

**Issue by ultimateshadsform** [mubaidr/vite-vue3-chrome-extension-v3#55]
Why does it generate src folder inside dist folder? Can it be fixed?
![image](https://github.com/mubaidr/vite-vue3-chrome-extension-v3/assets/151234273/42101b5e-86fe-479e-8b27-4aaa46a4273a)

**Comment by mubaidr** [comment]
You are right, this is bug in `vite` config. Currently the build system outputs `ts` files to `dist/src` directory too, which are not required. 

I will look into this issue.

**Comment by mubaidr** [comment]
should be fixed in: https://github.com/mubaidr/vite-vue3-chrome-extension-v3/commit/e171644c05793efdbf23b5b615ad81d40f681c9f

**Comment by ultimateshadsform** [comment]
I just cloned a new repo and it still has the `src` folder in the `dist` folder: 
![image](https://github.com/mubaidr/vite-vue3-chrome-extension-v3/assets/151234273/6b822882-a4e5-42d1-994e-d8a08681f6af)

Should it be like that?

I tried installed pnpm instead of yarn but it still created the dist folder in src

**Comment by mubaidr** [comment]
> I just cloned a new repo and it still has the `src` folder in the `dist` folder: ![image](https://private-user-images.githubusercontent.com/151234273/295149692-6b822882-a4e5-42d1-994e-d8a08681f6af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTEyMDAsIm5iZiI6MTcwNDc5MDkwMCwicGF0aCI6Ii8xNTEyMzQyNzMvMjk1MTQ5NjkyLTZiODIyODgyLWE0ZTUtNDJkMS05OTRlLWQ4YTA4NjgxZjZhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQwOTAxNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzE0MTU1NjJkYWY5OWUyMjA5Mjk5YTc1NzY2NWExNmY3Mzc0NTVlMTdkY2RiMjViYTU5ZjlmNzM0MmExN2JiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sVrhWDISlefQ4OdAUFN0FxlmLvFrLocDdbh08_jcOF0)
> 
> Should it be like that?
> 
> I tried installed pnpm instead of yarn but it still created the dist folder in src

`src` directory does exists and it's not a problem. We have html files included from src directory. So this is fine.

We should not have any extra (or non compiled files), which has been fixed in latest commit.

**Comment by ultimateshadsform** [comment]
Ahh okay!

Just wondering if it's possible to change the name of src to another name such as dist or something?

I could always just do a script anyways.

But thank you!

**Comment by mubaidr** [comment]
This should be possible, I will look into this.

**Comment by ultimateshadsform** [comment]
It's not really a big deal but I appreciate it!

It's just weird to me to have it named `src ` in production.
