### ISSUE TITLE
TODO Update to Vite 5

### ISSUE THREAD

**Issue by ultimateshadsform** [mubaidr/vite-vue3-chrome-extension-v3#58]
I have seen [https://github.com/crxjs/chrome-extension-tools](https://github.com/crxjs/chrome-extension-tools/releases) has updated and fixed the Vite 5 problem with `@crxjs/vite-plugin@2.0.0-beta.22` version.

> https://github.com/crxjs/chrome-extension-tools/commit/ce9fe1c351c2a90f7e445298345ef7c19438d204: Fix/web accessible resources script modules
https://github.com/crxjs/chrome-extension-tools/commit/48d8c68a69a6190d005875abe5f5813d3b94a83b: Vite 5 moved vite manifest from 'manifest.json' to
'.vite/manifest.json'. This change updates the plugin to use the new location
if Vite major version is >4, old location otherwise.

I haven't tested it yet but it's a goal.

**Comment by mubaidr** [comment]
Implemented in: https://github.com/mubaidr/vite-vue3-chrome-extension-v3/commit/f8a634e4066a979d1347dddedbaf0788abd39419

**Comment by ultimateshadsform** [comment]
> Implemented in: [f8a634e](https://github.com/mubaidr/vite-vue3-chrome-extension-v3/commit/f8a634e4066a979d1347dddedbaf0788abd39419)

That was quick!! 🥳🎉
