### ISSUE TITLE
Fix for the src problem

### ISSUE THREAD

**Issue by ultimateshadsform** [mubaidr/vite-vue3-chrome-extension-v3#65]
I have finally fixed it!

Move all html files outside src folder like this:

![image](https://github.com/mubaidr/vite-vue3-chrome-extension-v3/assets/151234273/a34a0eba-337c-42a9-98ea-8698cb53a124)

Add setup page to rollup:
![image](https://github.com/mubaidr/vite-vue3-chrome-extension-v3/assets/151234273/1be0f89b-bd60-46a2-b351-c8980966d13f)

Change ts path inside all html files to relative ts file:
![image](https://github.com/mubaidr/vite-vue3-chrome-extension-v3/assets/151234273/5898da5d-95b4-4b81-8ecd-0d01396195a4)

Now everything works as expected:
![image](https://github.com/mubaidr/vite-vue3-chrome-extension-v3/assets/151234273/560213fe-e837-4217-9cb9-a90269a036bb)

**Comment by ultimateshadsform** [comment]
Or should hmm still have some issue

**Comment by ultimateshadsform** [comment]
Also a life improvement you can add `include: ['vue', '@vueuse/core', 'vue-router', 'pinia']` to the include thing in vite config.

**Comment by mubaidr** [comment]
> I have finally fixed it!

Can you please tell me what problem you are trying to solve here?

I understand that this could be another way to organize project, but I just want to know what problem occurred.

**Comment by ultimateshadsform** [comment]
So you don't have src folder in production

**Comment by mubaidr** [comment]
To be honest, I don't like this pattern for two reasons: 
- literally there is no harm in having `src` directory in output folder. In fact, it may be helpful at times when you want to see what files are in distribution.
- Currently all related files are in one dir for each page (popup, setup etc). This make sure utilities and related script/ css and be placed next to these for ease & management.

**Comment by ultimateshadsform** [comment]
Yeah it's a preference.
